version: "3.9"

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    environment:
      - PYTHONPATH=/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - PYTHONPATH=/code
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: notification_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7.4.2

volumes:
  pgdata: